name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: tikhonovapolly/phigaro_test_for_git
    
    steps:
      - name: Download data
        run: |
          mkdir /home/data
          cd /home/data
          wget https://raw.githubusercontent.com/bobeobibo/phigaro/master/test_data_gitaction/latest_version.txt
          wget https://raw.githubusercontent.com/bobeobibo/phigaro/master/test_data_gitaction/test_short_seq.fasta
          cp -r /root/.phigaro ~/.phigaro
      - name: Test Phigaro at python2
        shell: bash
        run: |
          mkdir /home/outpy2
          /root/miniconda3/envs/python2/bin/pip install -r /home/data/latest_version.txt
          echo Run Phigaro
          /root/miniconda3/envs/python2/bin/python /root/miniconda3/envs/python2/bin/phigaro -f /home/data/test_short_seq.fasta -o /home/outpy2/output -e html txt gff bed --not-open 
          echo Deleting Phigaro
          /root/miniconda3/envs/python2/bin/pip uninstall phigaro -y
          echo Phigaro works fine at python2
      - name: Test Phigaro at python3
        shell: bash
        run: |
          mkdir /home/outpy3
          /root/miniconda3/envs/python3/bin/pip install -r /home/data/latest_version.txt
          echo Run Phigaro
          /root/miniconda3/envs/python3/bin/python /root/miniconda3/envs/python3/bin/phigaro -f /home/data/test_short_seq.fasta -o /home/outpy3/output -e html txt gff bed --not-open 
          echo Deleting Phigaro
          /root/miniconda3/envs/python3/bin/pip uninstall phigaro -y
          echo Phigaro works fine at python3

