name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: tikhonovapolly/phigaro_test_for_git

    steps:
    - uses: PollyTikhonova/phigaro_git_action@master
    - name: Test Phigaro at python3
      run:  conda env list
    - name: Test Phigaro at python2
      uses: PollyTikhonova/phigaro_git_action@master
      with:
          entrypoint: /home/test_python2.sh
