name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: PollyTikhonova/phigaro_git_action@master
    - name: Test Phigaro at python3
      uses: PollyTikhonova/phigaro_git_action@master
    - name: echo smth
      run: echo "smt h"
