name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: tikhonovapolly/phigaro_test_for_git
    
    steps:
      - name: Test Phigaro at python3 
        shell: bash
        uses: PollyTikhonova/phigaro_git_action@master
        with:
          entrypoint:  /home/test_python3.sh
      - name: Test Phigaro at python2
        shell: bash
        run: |
          /root/miniconda3/bin/conda activate python2
          /root/miniconda3/envs/python2/bin/pip install -r /home/latest_version.txt
          /root/miniconda3/envs/python2/bin/phigaro -f /home/test_short_seq.fasta -o /home/output -e html txt gff bed --not-open -d
          /root/miniconda3/envs/python2/bin/pip uninstall phigaro 
          /root/miniconda3/bin/conda deactivate
          echo Phigaro works fine at python2
