name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: PollyTikhonova/phigaro_git_action
    - name: Test Phigaro at python3
      run: |
        conda activate python3
        pip install -r /home/latest_version.txt
        phigaro -f /home/test_short_seq.fasta -o output -e html txt gff bed --not-open -d
        pip uninstall phigaro 
        conda deactivate
        echo Phigaro works fine at python3
    - name: Test Phigaro at python2
      run: |
        conda activate python2
        pip install -r /home/latest_version.txt
        phigaro -f /home/test_short_seq.fasta -o output -e html txt gff bed --not-open -d
        pip uninstall phigaro 
        conda deactivate
        echo Phigaro works fine at python2
