name: Phigaro Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: tikhonovapolly/phigaro_test_for_git
    
    steps:
      - name: Test Phigaro at python2
        shell: bash
        run: |
          /root/miniconda3/envs/python2/bin/pip install -r https://raw.githubusercontent.com/bobeobibo/phigaro/master/test_data_gitaction/latest_version.txt
          /root/miniconda3/envs/python2/bin/python /root/miniconda3/envs/python2/bin/phigaro -f /home/test_short_seq.fasta -o /home/output -e html txt gff bed --not-open 
          /root/miniconda3/envs/python2/bin/pip uninstall phigaro
          echo Phigaro works fine at python2
